database=mysql
spring.datasource.url=jdbc:mysql://34.131.253.174:3306/sharepic-case-study-datacenter
#spring.datasource.url=jdbc:mysql://google/sharepic-case-study-datacenter?cloudSqlInstance=sharepic-377714:asia-south2:sharepic-case-study-datacenter&socketFactory=com.google.cloud.sql.mysql.SocketFactory&requireSSL=false
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username: user
#spring.datasource.password: user
##CLOUD-SQL-CONFIGURATIONS
spring.cloud.gcp.sql.database-name=sharepic-case-study-datacenter
spring.cloud.gcp.sql.instance-connection-name=sharepic-377714:asia-south2:sharepic-case-study-datacenter
  # So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
  # Enforces database initialization
spring.datasource.initialization-mode=always
spring.datasource.username=gourav
spring.datasource.password=gourav
spring.cloud.gcp.project-id=sharepic-377714
#spring.jpa.hibernate.ddl-auto=update
spring.cloud.gcp.credentials.location=classpath:templates/sharepic-377714-b8b69f03f0a7.json